/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilterDialog: typeof import('./src/components/FilterDialog.vue')['default']
    GameAddForm: typeof import('./src/components/GameAddForm.vue')['default']
    GameEditForm: typeof import('./src/components/GameEditForm.vue')['default']
    MainAeraGameInfo: typeof import('./src/components/MainAeraGameInfo.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NOption: typeof import('naive-ui')['NOption']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSplit: typeof import('naive-ui')['NSplit']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SideBarGameList: typeof import('./src/components/SideBarGameList.vue')['default']
    SideBarNav: typeof import('./src/components/SideBarNav.vue')['default']
    SortDialog: typeof import('./src/components/SortDialog.vue')['default']
    Statistics: typeof import('./src/components/Statistics.vue')['default']
  }
}
